### ISSUE TITLE
Home page footer

### ISSUE THREAD

**Issue by KatieCardoza** [adrbrewer/assign_1_addie_taylor#13]
On the home page, the footer bar is above the footer and in the body text.  It might be that there are too many div tags and the computer isn't reading them correctly even though they're correct (with the styling I added it's easier to see this).  It also may be a conflict in the styling we're pulling and what we've written.  In short, I have no idea why it's messing up and would appreciate if someone else could take a look.  Thanks!

**Comment by Zeniwow** [comment]
Not entirely sure why, but the class="col-sm-6" was making the div area go below the overall section thus putting it below the footer and messing things up. Looks good now.
